@Catalog_HostAddress = https://localhost:7084/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/10
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
  "id": 10,
  "name": "New Product Sun Flashlight",
  "description": "This is a new product.",
  "price": 19.99,
  "imageUrl": "product10.png"
}

###

PUT {{Catalog_HostAddress}}/10
Content-Type: application/json
{
  "name": "Updated Product Sun Flashlight",
  "description": "This is an updated product.",
  "price": 24.99,
  "imageUrl": "product10_updated.png"
}

###

DELETE {{Catalog_HostAddress}}/10
Content-Type: application/json


